import type { Listing } from "@/lib/types";

export const sampleListings: Listing[] = [
  {
    id: "1",
    title: "Toyota Corolla 1.6 (2016) - Budapest",
    make: "Toyota",
    model: "Corolla",
    priceHuf: 3990000,
    year: 2016,
    mileageKm: 128000,
    fuel: "petrol",
    transmission: "manual",
    body: "sedan",
    location: "Budapest",
    powerKw: 97,
    displacementCcm: 1598,
    notes: "Service history, 2nd owner, city+highway use.",
    url: "https://example.com/listing/1",
  },
  {
    id: "2",
    title: "Honda Civic 1.8 (2014) - Pest county",
    make: "Honda",
    model: "Civic",
    priceHuf: 3290000,
    year: 2014,
    mileageKm: 154000,
    fuel: "petrol",
    transmission: "manual",
    body: "hatchback",
    location: "Pest",
    powerKw: 104,
    displacementCcm: 1798,
    notes: "Fresh TÜV, minor cosmetics.",
    url: "https://example.com/listing/2",
  },
  {
    id: "3",
    title: "Toyota Prius Hybrid (2015) - Győr",
    make: "Toyota",
    model: "Prius",
    priceHuf: 4650000,
    year: 2015,
    mileageKm: 210000,
    fuel: "hybrid",
    transmission: "cvt",
    body: "hatchback",
    location: "Győr-Moson-Sopron",
    notes: "Hybrid battery checked, taxi history unknown.",
    url: "https://example.com/listing/3",
  },
  {
    id: "4",
    title: "VW Golf 1.4 TSI (2017) - Szeged",
    make: "Volkswagen",
    model: "Golf",
    priceHuf: 4390000,
    year: 2017,
    mileageKm: 142000,
    fuel: "petrol",
    transmission: "automatic",
    body: "hatchback",
    location: "Csongrád-Csanád",
    notes: "DSG service documented.",
    url: "https://example.com/listing/4",
  },
  {
    id: "5",
    title: "Tesla Model 3 (2019) - Budapest",
    make: "Tesla",
    model: "Model 3",
    priceHuf: 11990000,
    year: 2019,
    mileageKm: 98000,
    fuel: "electric",
    transmission: "automatic",
    body: "sedan",
    location: "Budapest",
    notes: "Imported, fast charging enabled.",
    url: "https://example.com/listing/5",
  },
  {
    id: "6",
    title: "Toyota RAV4 Hybrid (2018) - Debrecen",
    make: "Toyota",
    model: "RAV4",
    priceHuf: 9990000,
    year: 2018,
    mileageKm: 175000,
    fuel: "hybrid",
    transmission: "cvt",
    body: "suv",
    location: "Hajdú-Bihar",
    notes: "Family car, highway mileage.",
    url: "https://example.com/listing/6",
  },
];

